# Site settings
title: Coding Velocity
email: chester.twomey@gmail.com
description: Coding at the velocity of awesome
twitter_username: CodingVelocity
github_username:  ctwomey1

markdown: kramdown
kramdown:
  input: GFM
  syntax-highlighter: rogue
