# Site settings
title: Git Cache
email: chester.twomey@gmail.com
description: Git Cache is a blog built on jekyll where i intend to stow all my interesting tech finds
twitter_username: ChesterTwomey
github_username:  ctwomey1

# Build settings
markdown: redcarpet
